### PR TITLE
Wlroots 0.4 Compatibility

### LINKED ISSUE #281: Fix touch_id compile issues
https://github.com/swaywm/wlroots-rs/blob/a1a5c25ea73581afaf45fa524f9fc7412b18bb40/src/types/seat/drag_icon.rs#L48

`touch_id` was moved to the `wlr_drag` structure in `wlr_drag_icon`. Compiler fusses about this. Mainly using this as a reference to fix later.

### PR DESCRIPTION
**Pull request by SethBarberee**
Fixes #281

### CODE REVIEW

**Comment by SethBarberee** [comment]
Wlroots 0.4 introduces the change. CI is still on 0.3 hence the error

**Comment by Timidger** [comment]
If this is a breaking change for 0.4, can you instead update the `wlroots` submodule in wlroots-sys/ and fix all the breakage? That way the upgrade is atomic and I can tag it.

**Comment by Timidger** [comment]
Can you fix the other breakage if you are going to be updating this to 0.4? According to the build there's two other breaking changes.

**Comment by SethBarberee** [comment]
One of the two errors is fixed. The other is a lot of things... The refractor from https://github.com/swaywm/wlroots/pull/1517 changed lots of things relating to it. Looking at the code rn

**Comment by Timidger** [comment]
Data device wasn't ever fully wrapped, so if that isn't compiling you can probably just delete the code and it can be re-added later. That would mean the only remaining changes are to seat.

**Comment by Timidger** [comment]
Once conflicts have been resolved this should be good to go.

**Comment by SethBarberee** [comment]
I'm gonna do a rebase/squash to silence this

**Comment by SethBarberee** [comment]
Should be all good now. Had to fight git a little

**Comment by Timidger** [comment]
Looks like there are some warnings about unused methods in `drag_icon_handler.rs`.

Normally I wouldn't mind since I was planning on fixing this at some point or another, but since this is a release I don't want those appearing when people pull the crate. Can you fix them? Just delete the code it is complaining is dead should be sufficient, it needs to be rewritten in the future anyways.

**Comment by Timidger** [comment]
Also I should probably have the CI deny warnings... #286

**Comment by Timidger** [comment]
Thanks!

**Pull request merged**
