### PR TITLE
Feature/server decoration wrapper

### PR DESCRIPTION
**Pull request by alexander-smoktal**
Server decoration protocol wrapper.
Relates to #10

### CODE REVIEW

**Comment by Timidger** [comment]
Awesome, thanks.

I think you need to make that enum repr(C) / you need to specify the type when passing it to C. I haven't done that before though, so you might want to double check what annotations are required on an enum value that you will pass to C

**Comment by Timidger** [comment]
Can you fix the build for wlroots since you updated the hash? They renamed `wlr_data_device_manager.h` to simply `wlr_data_device.h` and that broke the build.

**Comment by alexander-smoktal** [comment]
Fixed header.

Do you mean `wlr_server_decoration_manager_set_default_mode` function? The problem is that I can't find that enum. There's only one usage of the function and it uses `ORG_KDE_KWIN_SERVER_DECORATION_MANAGER_MODE_CLIENT`, which I wasn't able to find. 
I suppose, this constant was generated by protocol generator. In this case I have no idea how to use it inside Rust.

**Comment by alexander-smoktal** [comment]
Why did Travis failed? I can't see an error.

**Comment by Timidger** [comment]
> Why does Travis fail? I can't see an error.

It's cargo fmt complaining. Please ensure you have the latest version of rustfmt installed for nightly and run `cargo fmt`.

> Do you mean wlr_server_decoration_manager_set_default_mode function? The problem is that I can't find that enum. There's only one usage of the function and it's ORG_KDE_KWIN_SERVER_DECORATION_MANAGER_MODE_CLIENT, which I wasn't able to find.

We may not be exposing it in wlroots-sys. Double check that it falls under the filter rules specified in `wlroots-sys/build.rs`. If it shows up in a header that we include it should be showing up unless it's being filtered out by those rules. I can take a look later tonight and try to find it

**Comment by alexander-smoktal** [comment]
> We may not be exposing it in wlroots-sys. Double check that it falls under the filter rules specified in wlroots-sys/build.rs. If it shows up in a header that we include it should be showing up unless it's being filtered out by those rules. I can take a look later tonight and try to find it

Here they are:
```
$ find -name server-decoration-protocol.h
./build/examples/screenshot@exe/server-decoration-protocol.h
./build/types/wlr_types@sta/server-decoration-protocol.h
./build/backend/wlr_backend@sta/server-decoration-protocol.h
./build/protocol/wl_protos@sta/server-decoration-protocol.h
./build/rootston/rootston@exe/server-decoration-protocol.h
```
But they're in build directory. What's the proper way to include them? Because we don't know, which location they will be generated in. Right?

Maybe generate them again with https://crates.io/crates/wayland-scanner?

**Comment by Timidger** [comment]
Ah, didn't realise they were part of the protocol (sorry, I should have looked at that closer!).

Yes, use Wayland-scanner crate to generate the definition for that enum

**Comment by alexander-smoktal** [comment]
Wayland scanner fails to generate interfaces: 
```
thread 'main' panicked at 'Ill-formed protocol file: Some(Ok(CData(
    Copyright (C) 2015 Martin Gräßlin

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 2.1 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
  )))', /home/cosm/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-scanner-0.12.2/src/parse.rs:70:40
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

And it's because of `<![CDATA[` inside protocol copyright. What to do?

I can try to use `generate_code_streams` with some XML parser?

**Comment by Timidger** [comment]
@alexander-smoktal Hmm. I suggest raising an issue with wayland-scanner. If this is valid xml, it should parse it correctly. If it is invalid, we should raise the issue with the copyright holder / wlroots (as they may have a way to work around it as well, e.g maybe we can get wayland-scanner to ignore the copyright).

For now, if you want to test the generation/actual code I suggest removing the erroneous inner element. I won't merge it in until we fix the copyright though

**Comment by Timidger** [comment]
@alexander-smoktal Added patch to wayland-scanner that fixes your issue https://github.com/Smithay/wayland-rs/pull/159

**Comment by Timidger** [comment]
Looks good, thanks a bunch! I'll fix the wayland-sys version once a release is cut for that.

**Pull request merged**
