### PR TITLE
Use pkg-config to find the share dir for wayland-protocols

### PR DESCRIPTION
**Pull request by carlosdagos**
Hello! Thanks a lot for wlroots :smile: 

This was failing to compile on my system (NixOS) because of this hardcoded path. This patch fixes that, at least if `wayland-protocols` is known to pkg-config. Hope it works well.

### CODE REVIEW

**Comment by Timidger** [comment]
Thanks! I'll manually build it after work since I haven't fixed the ci yet. Assuming it builds I'll merge it then. 

Also FYI these are just bindings, my work on wlroots itself is minimal compared to the sway developers.

**Comment by carlosdagos** [comment]
Cheers @Timidger :)

Looks like the examples fail to build. I actually saw this on my computer as well and was gonna open a second PR to fix the examples, but I'm not sure about https://github.com/swaywm/wlroots-rs/blob/master/examples/simple.rs with the `gl` functions. I'll get there though :D

**Comment by Timidger** [comment]
Ah that's been an issue since before your patch...crap.

I can't actually fix this right now [due to legal reasons](http://way-cooler.org/blog/2018/07/27/prehibernate-update.html).

For any one who wants to fix this:
* fix the macros by adding a `$crate` to the offending libc line for `c_str` definition
* For the simple example...honestly not sure how long that's been broken, but that example can probably just be removed since there's others now.

**Comment by carlosdagos** [comment]
I think the examples should be fixed in the last commit @Timidger. I just removed the `simple` one :smile: 

Let me know if it works for you :+1: Cheers

**Comment by Timidger** [comment]
Ok looks good to me, thanks!

**Pull request merged**
